FROM ruby:3.3.6
ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

# 基本的な依存関係のインストール
RUN apt-get update -qq && apt-get install -y \
    build-essential \
    libpq-dev \
    nodejs \
    yarn \
    vim \
    wget \
    unzip \
    gnupg

# Chromium と Chromium ドライバーのインストール
RUN apt-get update -qq && apt-get install -y \
    chromium \
    chromium-driver

# 作業ディレクトリの作成
RUN mkdir /myapp
WORKDIR /myapp

# Bundler のインストール
RUN gem install bundler

# アプリケーションコードのコピー
COPY . /myapp

# アプリケーションの依存関係をインストール
RUN bundle install
